FROM ubuntu:20.04

# Install ssh server
RUN apt update &&\
apt install openssh-server sudo -y &&\
apt clean

# Create user
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test &&\
echo 'test:test' | chpasswd

# Run ssh server
RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
